sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mrydeen/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mrydeen/docker-react npm run test